
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include: oauth,key
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/datajpa
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true


logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace


server:
  port: 8081
